repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.5.0
    hooks:
    - id: check-merge-conflict
    - id: check-toml
    - id: check-yaml
    - id: end-of-file-fixer
    - id: mixed-line-ending
    - id: trailing-whitespace
  - repo: https://github.com/psf/black.git
    rev: 23.11.0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/charliermarsh/ruff-pre-commit.git
    rev: v0.1.6
    hooks:
      - id: ruff
        args:
          - "--fix"
  - repo: https://github.com/pre-commit/mirrors-prettier.git
    rev: v3.1.0
    hooks:
      - id: prettier
        types: [json]
