repos:
  - repo: https://github.com/psf/black.git
    rev: 22.10.0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/PyCQA/isort.git
    rev: 5.10.1
    hooks:
      - id: isort
        args: ['--profile', 'black', '--filter-files']
