name: Docker Publish
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: biggates/esp-idf-devcontainer


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    strategy:
      matrix:
        idf_version: ["5.2.2"]
        qemu_version: ["20240606"]
        include:
        - qemu_version: "20240606"
          qemu_release: "esp_develop_9.0.0_20240606"
          qemu_dist: "qemu-xtensa-softmmu-esp_develop_9.0.0_20240606-x86_64-linux-gnu.tar.xz"
          qemu_sha256: "071d117c44a6e9a1bc8664ab63b592d3e17ceb779119dcb46c59571a4a7a88c9"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Download qemu
        run: |
          wget -q -S -O qemu.tar.gz https://github.com/espressif/qemu/releases/download/${{ matrix.qemu_release }}/${{ matrix.qemu_dist }}

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build and push docker image
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: biggates/esp-idf-devcontainer:idf_{{ matrix.tag }}_qemu_{{ matrix.qemu_version }}
          build-args: |
            IDF_VERSION=${{ matrix.idf_version }}
            QEMU_SHA256=${{ matrix.qemu_sha256 }}
